### ISSUE TITLE
Chrome: clicking on a tag in the structure panel no longer turns it bold

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-Writer#360]

**Comment by ajmacdonald** [comment]
Should be fixed.

**Comment by ilovan** [comment]
Nope, still happening  (even after I cleaned my cache)

**Comment by ajmacdonald** [comment]
This is probably a Mac specific issue. Unfortunately I don't have a Mac to test/debug it.

**Comment by jchartrand** [comment]
Mihaela, just to be sure we’re all talking about the same page, could you include the link to the version of the editor you’re testing.

**Comment by ilovan** [comment]
CWRC-Writer version: Dev
Browser: Chrome
OS X 10.7.5 and also 10.9.5
All schemas supported.

(It's still happening now)

**Comment by SusanBrown** [comment]
I think its fixed. Colin and Cailin please test.

**Comment by SusanBrown** [comment]
@cailinr please test

**Comment by cailinr** [comment]
This seems to be fixed. Tested in firefox and chrome @SusanBrown
